### ISSUE TITLE
Does LegoOS support socket programming? Memory node failed to compile...

### ISSUE THREAD

**Issue by fyc1007261** [WukLab/LegoOS#14]
Hi @lastweek  @hythzz ,

Thanks so much for your previous help! Our group is currently trying to make some more complex applications with socket programming to run on LegoOS. We set `CONFIG_SOCKET_O_IB=y`  on all three (1P-1M-1S) nodes and enabled the `SOCKET_SYSCALL` configuration on the processor node.  The processor node worked fine, while the memory node failed to compile with the message 
```shell
net/built-in.o: In function `ibapi_sock_send_message':
/users/yifancai/LegoOS.skt/net/lego/fit_ibapi.c:268: undefined reference to `sock_send_message'
net/built-in.o: In function `ibapi_sock_receive_message':
/users/yifancai/LegoOS.skt/net/lego/fit_ibapi.c:274: undefined reference to `sock_receive_message'
```

I tried to modify some code to let the code finds the definitions, but more errors occurred... Does LegoOS currently support socket programming? If so, is there any other configurations that I should change?

Thanks again!

**Comment by lastweek** [comment]
Hi @fyc1007261, sorry for the late reply. Socket programming is not supported for now. We have some syscalls, but some of them are a bit buggy, not reliable enough. Having a direct Socket over IB solution would be nice, but we didn't have enough time to work on this before. Speaking of which, a SIGCOMM'19 paper has worked on this https://www.microsoft.com/en-us/research/publication/socksdirect-datacenter-sockets-can-be-fast-and-compatible/

**Comment by fyc1007261** [comment]
Hi @lastweek ,
Thanks for your information!
