### ISSUE TITLE
Compile Error with 1P-1M Setting

### ISSUE THREAD

**Issue by Monotrea** [WukLab/LegoOS#5]
I encountered a compile error for both processor and memory manager.  
I used Oracle VirtualBox(v5.2.22) and Vagrant(v2.2.1) and the guest OS was CentOS-7.2.  
The main problem might be a configuration setting. I executed commands like below with root user.  

```
make defconfig
cp Documents/configs/1P-1M-(Processor|Memory) .config
make
```

For the last "make" command , I had the error below. For this error, I could solve this by commenting out this line (Line 39) in "managers/common.c", because I thought there was no need to consider storage manager for 1P-1M model. Is there any problem with this solution?

```
...
  CC      managers/common.o
managers/common.c:39:3: Error: #error "Please adjust default storage node."
 # error "Please adjust default storage node."
   ^
make[1]: *** [managers/common.o] Error 1
make: *** [managers] Error 2
```

And for memory manager, I had another error like below. I think this is caused by the wrong order of compiling codes described in Makefile.  
How can it be fixed? Or could you tell me the stable version of LegoOS? In this case, what version did you use to evaluate the performance of this OS in the article(OSDI '18)?  
Finally, can LegoOS be tested with processor manager and memory manager running on different nodes on the same server?  
Sorry for asking many questions, but I hope you will answer them.

```
...
  AS      managers/memory/ramfs/piggy.o
managers/memory/ramfs/piggy.S: Assembler messages:
managers/memory/ramfs/piggy.S:15: Error: file not found: usr/general.o
make[3]: *** [managers/memory/ramfs/piggy.o] Error 1
make[2]: *** [managers/memory/ramfs] Error 2
make[1]: *** [managers/memory] Error 2
make: *** [managers] Error 2
```

**Comment by lastweek** [comment]
Hi @Monotrea,

Thanks for trying out LegoOS.

Your fix to processor side is correct. In fact, this issue was brought by me in some previous changes. I just fixed this issue in the latest commit:https://github.com/WukLab/LegoOS/commit/7d805757ddd03c57a04ba86b9b829db7b97e7206

As for the memory manager part, the compiler is complaining that it can not find the user program that is linked into the final bzImage. You need to compile `user/general.o` first. You can do:
```
cd usr/
make
cd ..
make
```
Sorry I did not say this clearly in the README.

Current version is stable. It's just some of my recent changes for open-source break some of the compiling process.

**Comment by lastweek** [comment]
Q: `can LegoOS be tested with processor manager and memory manager running on different nodes on the same server?`

A: Unfortunately, no. You need at least two physical machines. Even if you are running LegoOS within VM, these two VMs have to run on different host machines.

**Comment by lastweek** [comment]
Q: ` Or could you tell me the stable version of LegoOS? In this case, what version did you use to evaluate the performance of this OS in the article(OSDI '18)?`

A: We used this [v0.1.1-excache](https://github.com/WukLab/LegoOS/releases/tag/v0.1.1-excache) to get all the numbers in paper. We don't have any code changes after that. So you can use current HEAD.

**Comment by Monotrea** [comment]
I appreciate your detailed replies to all of my questions. I'll continue trying LegoOS.

**Comment by Monotrea** [comment]
I try to generate general.o first, but it doesn't work as expected.
I have an error saying __NR_pcache_stat is not declared. This appears in "usr/includeme.h". What does this mean?
https://github.com/WukLab/LegoOS/blob/352a2db29804ea9948ee5897d44f603a164314e2/usr/includeme.h#L114

**Comment by lastweek** [comment]
This syscall number is auto-generated when you do a make.
You can go to `LegoOS/`, and type `make`. You will see several files generated, including `include/generated/unist_64.h`. This `make` may fail, it is okay, we just need the above header file.

Now go to `LegoOS/usr`, and type `make`

**Comment by Monotrea** [comment]
Thanks a lot. Memory manager compile succeeded without compile errors.

**Comment by Monotrea** [comment]
Processor manager on VM shows the message "Please wait for enough IB MAD (number 7)."
However, memory manager on VM has a kernel panic, and on physical machine it's also aborted. It says it can't allocate thpool buffer array. 
What kind of settings or configs could you please tell me may affect this error?

![screenshot from 2018-11-30 19 04 21](https://user-images.githubusercontent.com/18698446/49282607-ee1d3080-f4d2-11e8-911d-f4d4bf251450.png)
![screenshot from 2018-11-30 19 01 03](https://user-images.githubusercontent.com/18698446/49282594-e65d8c00-f4d2-11e8-855f-eee5b7b8ab85.png)

**Comment by lastweek** [comment]
Processor is now waiting for IB switch's MAD message. It should proceed after a while.

Memory side error happens https://github.com/WukLab/LegoOS/blob/master/managers/memory/core.c#L519. It is trying to allocate a big static buffer array. This function is called during early boot. Its failure means there is not enough memory. I suspect your VM does not have a lot Memory. It's suggested to have more than 2 vCPUs, and 2-4GB Memory.

**Comment by Monotrea** [comment]
Thank you for your answer. I tried to increase memory setting for VM and it worked as expected.

**Comment by Monotrea** [comment]
I know README says Infiniband NIC is needed, but is there really no support for ethernet connection among machines? (Sorry for asking very basic question.)

**Comment by lastweek** [comment]
Hi @Monotrea,

LegoOS do support e1000, the very basic ethernet device. But this ETH is used by socket layer.

The fundamental communication channel between LegoOS managers is via Infiniband NIC (the FIT layer). That means LegoOS can NOT run without a working Infiniband network.

We are sorry for this. There are several limitations we want to address, but due to limited time and bandwidth, we have not solved them yet.

**Comment by Monotrea** [comment]
Hello, @lastweek,
OK, I got it.
Thank you for your helpful answer.

**Comment by Monotrea** [comment]
Hi, @lastweek,
I find that prefetch.c (`LegoOS/managers/processor/pcache/prefetch.c`) has no function.
However, a config file has `CONFIG_PCACHE_PREFETCH` option.
I wonder if LegoOS has an ExCache(`pcache`) prefetching mechanism or not.

**Comment by lastweek** [comment]
Hi @Monotrea ,

We don't support prefetch now. I should get rid of that. Sorry for the confusion.

**Comment by Monotrea** [comment]
Thank you for your answer. I think that evict_random.c is evict_fifo.c, isn't it?

**Comment by lastweek** [comment]
evict_random.c and evict_fifo.c are broken code, don't use them.

evict_lru.c can offer both LRU and FIFO, when configured accordingly
- Offers LRU: if `CONFIG_PCACHE_EVICT_GENERIC_SWEEP=y`
- Offers FIFO: if `CONFIG_PCACHE_EVICT_GENERIC_SWEEP` is not configured

The sweep option will create a new thread that keep sweeping the PTEs to adjust the LRU list. If the sweep is off, it's basically FIFO.

**Comment by Monotrea** [comment]
I appreciate your reply. I got it.

**Comment by Monotrea** [comment]
Sorry for forgetting closing this issue so long.
If I have another question, I will open a new issue.
I deeply appreciate your replies and kindness.
