### ISSUE TITLE
Compile error when building `linux-kernel` on storage node

### ISSUE THREAD

**Issue by fyc1007261** [WukLab/LegoOS#7]
The `ib_alloc_pd` function should be declared in LegoOS' `ib_verbs.h`. However, when compiling on my machine, it goes to the CentOS kernel's `ib_verbs.h`, which has different interface and different meanings. I wonder whether there is any error with the makefile of the `linux-module`.

**Comment by lastweek** [comment]
Hi @fyc1007261 ,

Can you share the Linux kernel version you are using? Kernel IB API has been changed a lot. Current repo's linux-module code works best with 3.11.1 kernel.

**Comment by fyc1007261** [comment]
> Hi @fyc1007261 ,
> 
> Can you share the Linux kernel version you are using? Kernel IB API has been changed a lot. Current repo's linux-module code works best with 3.11.1 kernel.

Thanks! However, I have been faced with some problems with installing 3.11.1 kernel on the server. Is it possible to simply run a 1P-1M model only involving the 3.10.0 kernel? I suggest I will be using the storage components and global resource manager so that it will be ok...?

**Comment by lastweek** [comment]
It's possible to just run 1P-1M configuration, see the instructions here: https://github.com/WukLab/LegoOS#1p-1m.

It's a bit tricky to setup everything and get running, let me know if you have issues.
